### ISSUE TITLE
Collection size is not changing when new vectors are added.

### ISSUE THREAD

**Issue by kukirokuk** [zilliztech/attu#380]
Collection size is not changing when new vectors are added.

**Steps to reproduce:**
Add new vectors with pymilvus. Chek size.

**Attu version:**
2.3.6

**Comment by shanghaikid** [comment]
The count number on collection page is an approximation and may be slightly delayed due to the unique mechanisms of Milvus. The actual count may vary and is updated periodically. Please note that this number should be used as a reference and not as an exact count.


If you load the collection, please check this count, it should be correct. 
![image](https://github.com/zilliztech/attu/assets/185051/861911b6-7bf8-4055-ada7-3e2cb366a919)


Here is an  article about data consistency in milvus.
https://milvus.io/docs/consistency.md.
